### ISSUE TITLE
Documentation for each component

### ISSUE THREAD

**Issue by Macxim** [lipsumar/design-system-framework#4]
Where am I supposed to write documentation for each component?

The section under the component with the two tabs _Documentation_ and _Source_ displays static information and not data about the component displayed above.

**Comment by lipsumar** [comment]
The plan is to have a markdown file in the component's directory.
The UI would load it via ajax from the server in the section you mention.
I try not to force the UI as much as possible, so just as the components are individually accessible at `http://localhost:3000/build/<componentId>`, the doc would follow the same approach.

**Comment by Macxim** [comment]
That sounds good!
I agree, most people would want be able to customize the UI (brand logo, font, colors, etc.).

I think your last point is worth mentioning in the README file.

**Comment by lipsumar** [comment]
As for the style of the UI itself, well, it will soon have its own repo and be developed using... DSF ;)

**Comment by lipsumar** [comment]
Documentation is now a native plugin of DSF.
