### ISSUE TITLE
Better name for the project

### ISSUE THREAD

**Issue by Macxim** [lipsumar/design-system-framework#7]
As nicely put in the wiki...

> First of all, the name sucks. It's probably not even a framework per say. Anyhow, until a cooler name is decided, the full name is "Design System Framework", short is DSF. It's more a code name for now. Ideas welcome!

**Comment by lipsumar** [comment]
The first thought I have about this project is that it's pretty anti-shiny in 2016: we're very far from a Polymer or React. It is also why this project exist! To regain some **sanity** in front-end development.

**Comment by lipsumar** [comment]
I keep coming back to this idea of simplicity as a core characteristic of DSF. It simplifies the source code and the final product. I know it's not very original, but I think about a box. I actually can't take this one out of my head http://www.flexboxpatterns.com/ ^^

**Comment by lipsumar** [comment]
Few days later, i want to change some features:
- no sass or postcss support => gulp plugins support;
- no built-in Handlebars => dsf plugins (currently hooks #24).

It becomes more agnostic and can focus on the core features:

DSF is like a robot sitting by your side: tell it how you work and it will watch you code and rebuild only what is needed while you work. Work with it and everyone can use the component library: back-end devs, designers and editors.

It helps working with web components for **websites**. If you're making a javascript-dependant webapp, then webpack is probably a better idea. Key points:
- web components
- live automation (as you code)
- component library UI
- agnostic (unopinionated)

**Comment by lipsumar** [comment]
Component Shop

**Comment by lipsumar** [comment]
I think I'll go with **Gregor**.
